openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione degli indirizzi degli ENTI

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /indirizzoFromCF/{codice_fiscale}:
    get:
      description: consultazione dell'indirizzo di un ENTE dato il codice fiscale

      operationId: getIndirizzoFromCF

      parameters:
        - name: codice_fiscale
          in: path
          description: Codice fiscale ENTE per il quale si effettua la ricerca
          required: true
          schema:
            $ref: '#/components/schemas/CodiceFiscaleEnte'
          example: 12345678901
            
      responses:
        '200':
          description: JSON dell'indirizzo estratto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
  /indirizzoFromCodiceIPA/{codice_ipa}:
    get:
      description: consultazione dell'indirizzo di un ENTE dato il codice ipa

      operationId: getIndirizzoFromCodiceIPA

      parameters:
        - name: codice_ipa
          in: path
          description: Codice IPA dell'ENTE per il quale si effettua la ricerca
          required: true
          schema:
            $ref: '#/components/schemas/CodiceIPA'
          example: agid
            
      responses:
        '200':
          description: JSON dell'indirizzo estratto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
components:

  responses:
    '400':
      description: BAD_REQUEST
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '401':
      description: UNAUTHORIZED
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: FORBIDDEN
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: NOT_FOUND
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: INTERNAL_SERVER_ERROR
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '503':
      description: SERVICE_UNAVAILABLE
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    CodiceFiscaleEnte:
      description: Codice Fiscale dell'ENTE      
      type: string
      pattern: ^([0-9]{11})$
      example: 12345678901

    CodiceIPA:
      description: codice ipa ENTE
      type: string
      maxLength: 100

    Address:
      description: Indirizzo dell'ENTE
      required:
        - codice_fiscale_ente
        - codice_ipa_ente
        - codice_istat_comune
        - codice_catastale_comune
        - CAP
        - address
        
      type: object
      properties:
        codice_fiscale_ente:
          description: codice fiscale dell'ENTE
          $ref: '#/components/schemas/CodiceFiscaleEnte'
        codice_ipa_ente:
          description: codice IPA dell'ENTE
          $ref: '#/components/schemas/CodiceIPA'
        codice_istat_comune:
          description: codice istat del Comune della sede dell'ENTE
          type: string
          maxLength: 6        
        codice_catastale_comune:
          description: codice catastale del Comune della sede  dell'ENTE
          type: string
          maxLength: 4        
        CAP:
          description: CAP del Comune della sede dell'ENTE
          type: string
          pattern: ^([0-9]{5})$
        address:
          description: indirizzo della sede dell'ENTE
          type: string
          maxLength: 246 

    Error:  
      description: Modello di risposta in caso di errore    
      required:
        - status
        - type
      type: object
      properties:
        status:
          type: string
          description: Codice di errore
          example: <HTTP_CODE>
          enum:
            - '400'
            - '401'
            - '403'
            - '404'
            - '500'
            - '503'
        type:
          type: string
          description: Tipologia di errore
          example: <HTTP_STATUS>
          enum:
            - BAD_REQUEST
            - UNAUTHORIZED
            - FORBIDDEN
            - NOT_FOUND
            - INTERNAL_SERVER_ERROR
            - SERVICE_UNAVAILABLE
        detail:
          type: string
          description: Descrizione di dettaglio dello specifico problema verificatosi
          example: <detail_error>
      
    
  securitySchemes:
    bearerAuth:
      scheme: bearer
      bearerFormat: JWT
      type: http
      description: |-
        Implementazione conforme ad RFC8725.

security:
  - bearerAuth: []