openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione delle AOO degli ENTI

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /AOOEnteFromCF/{codice_fiscale}:
    get:
      description: consultazione delle AOO di un ENTE dato il codice fiscale dello stesso

      operationId: getAOOEnteFromCF

      parameters:
        - name: codice_fiscale
          in: path
          description: Codice fiscale ENTE
          required: true
          schema:
            $ref: '#/components/schemas/CodiceFiscaleEnte'          
            
      responses:
        '200':
          description: array delle anagrafiche delle AOO di un ENTE
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AOOs'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
  /AOOEnteFromCodiceIPA/{codice_ipa}:
    get:
      description: consultazione delle AOO di un ENTE dato il codice ipa dello stesso

      operationId: getAOOEnteFromCodiceIPA

      parameters:
        - name: codice_ipa
          in: path
          description: Codice IPA dell'ENTE per il quale si effettua la ricerca
          required: true
          schema:
            $ref: '#/components/schemas/CodiceIPA'
          example: agid
            
      responses:
        '200':
          description: array delle anagrafiche delle AOO di un ENTE
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AOOs'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'

  /status:
    $ref: './common/pathStatus.yaml'
  
components:

  responses:
    $ref: './common/response.yaml'     

  schemas:
    CodiceFiscaleEnte:
      $ref: './common/schemaCodiceFiscaleEnte.yaml'

    CodiceIPA:
      $ref: './common/schemaCodiceIPA.yaml'

    AOO:
      $ref: './common/schemaAOO.yaml'
    
    AOOs:      
      type: array
      items:
        $ref: '#/components/schemas/AOO'
    
    Error:
      $ref: './common/schemaError.yaml'

  securitySchemes:
    $ref: './common/securitySchemes.yaml'

security:
  - bearerAuth: []