openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione degli ENTI

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /enteFromCF/{codice_fiscale}:
    get:
      description: consultazione di un ENTE dato il codice fiscale

      operationId: getEnteFromCF

      parameters:
        - name: codice_fiscale
          in: path
          description: Codice fiscale ENTE 
          required: true
          schema:
            $ref: '#/components/schemas/CodiceFiscaleEnte'
            
      responses:
        '200':
          description: anagrafica dell'ENTE 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ente'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
  /enteFromCodiceIPA/{codice_ipa}:
    get:
      description: consultazione di un ENTE dato il codice ipa

      operationId: getEnteFromCodiceIPA

      parameters:
        - name: codice_ipa
          in: path
          description: Codice IPA dell'ENTE 
          required: true
          schema:
            $ref: '#/components/schemas/CodiceIPA'          
            
      responses:
        '200':
          description: anagrafica dell'ENTE
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ente'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'

  /status:
    $ref: './common/pathStatus.yaml'
  
components:

  responses:
    $ref: './common/response.yaml'

  schemas:
    CodiceFiscaleEnte:
      $ref: './common/schemaCodiceFiscaleEnte.yaml'

    CodiceIPA:
      $ref: './common/schemaCodiceIPA.yaml'

    Ente:
      $ref: './common/schemaEnte.yaml'
        
    Error:
      $ref: './common/schemaError.yaml'      
    
  securitySchemes:
    $ref: './common/securitySchemes.yaml'

security:
  - bearerAuth: []