openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione dei domicili digitali delle AOO

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /DDAOO/{codice_uni_aoo}:
    get:
      description: consultazione dei domicili digitali delle AOO

      operationId: getDDAOO

      parameters:
        - name: codice_uni_aoo
          in: path
          description: Codice unico dell'AOO
          required: true
          schema:
            $ref: '#/components/schemas/CodiceUniAOO'

          example: 12345678901
            
      responses:
        '200':
          description: array JSON dei domicili digitali di una AOO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DDs'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'

components:

  responses:
    $ref: './common/response.yaml'

  schemas:
   CodiceUniAOO:
      $ref: './common/schemaCodiceUniAOO.yaml'
    
    DigitalAddress:
      $ref: './common/schemaDigitalAddress.yaml'

    DDs:
      description: array dei domicili digitali      
      type: array
      items:
        $ref: '#/components/schemas/DigitalAddress'
    
    Error:
      $ref: './common/schemaError.yaml'
      
  securitySchemes:
    $ref: './common/securitySchemes.yaml'

security:
  - bearerAuth: []