openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione dei domicili digitali degli ENTI

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /DDEnteFromCF/{codice_fiscale}:
    get:
      description: consultazione dei domicili digitali di un ENTE dato il codice fiscale

      operationId: getDDEnteFromCF

      parameters:
        - name: codice_fiscale
          in: path
          description: Codice fiscale ENTE per il quale si effettua la ricerca
          required: true
          schema:
            $ref: '#/components/schemas/CodiceFiscaleEnte'
          example: 12345678901
            
      responses:
        '200':
          description: array JSON dei domicili digitali di un ente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DDs'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
  /DDEnteFromCodiceIPA/{codice_ipa}:
    get:
      description: consultazione dei domicili digitalidi un ENTE dato il codice ipa

      operationId: getDDEnteFromCodiceIPA

      parameters:
        - name: codice_ipa
          in: path
          description: Codice IPA dell'ENTE per il quale si effettua la ricerca
          required: true
          schema:
            $ref: '#/components/schemas/CodiceIPA'
          example: agid
            
      responses:
        '200':
          description: array JSON dei domicili digitali di un ente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DDs'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
components:

  responses:
    $ref: './common/response.yaml'

  schemas:
    CodiceFiscaleEnte:
      $ref: './common/schemaCodiceFiscaleEnte.yaml'
    
    CodiceIPA:
      $ref: './common/schemaCodiceIPA.yaml'

    DigitalAddress:
      $ref: './common/schemaDigitalAddress.yaml'

    DDs:
      description: array dei domicili digitali      
      type: array
      items:
        $ref: '#/components/schemas/DigitalAddress'
    
    Error:
      $ref: './common/schemaError.yaml'
    
  securitySchemes:
    $ref: './common/securitySchemes.yaml'

security:
  - bearerAuth: []