openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione degli ENTI

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /enteFromCF/{codice_fiscale}:
    get:
      description: consultazione di un ENTE dato il codice fiscale

      operationId: getEnteFromCF

      parameters:
        - name: codice_fiscale
          in: path
          description: Codice fiscale ENTE per il quale si effettua la ricerca
          required: true
          schema:
            $ref: '#/components/schemas/CodiceFiscaleEnte'
          example: 12345678901
            
      responses:
        '200':
          description: JSON dell'ENTE estratto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ente'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
  /enteFromCodiceIPA/{codice_ipa}:
    get:
      description: consultazione di un ENTE dato il codice ipa

      operationId: getEnteFromCodiceIPA

      parameters:
        - name: codice_ipa
          in: path
          description: Codice IPA dell'ENTE per il quale si effettua la ricerca
          required: true
          schema:
            $ref: '#/components/schemas/CodiceIPA'
          example: agid
            
      responses:
        '200':
          description: JSON dell'ENTE estratto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ente'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
components:

  responses:
    $ref: './common/response.yaml'

  schemas:
    CodiceFiscaleEnte:
      $ref: './common/schemaCodiceFiscaleEnte.yaml'

    DigitalAddress:
      $ref: './common/schemaDigitalAddress.yaml'
      
    CodiceIPA:
      $ref: './common/schemaCodiceIPA.yaml'

    Ente:
      description: ENTE
      required:
        - codice_fiscale_ente
        - codice_ipa_ente
        - denomination
        - category_type
        - category_code
        - category_name       
      type: object
      properties:
        codice_fiscale_ente:
          description: codice fiscale dell'ENTE
          $ref: '#/components/schemas/CodiceFiscaleEnte'
        codice_ipa_ente:
          description: codice IPA dell'ENTE
          $ref: '#/components/schemas/CodiceIPA'
        denomination:
          description: denominazione dell'ENTE
          type: string
          maxLength: 1000
        category_type:
          description: tipologia della categoria dell'ENTE
          type: string
          maxLength: 140
        category_code:
          description: codice della categoria dell'ENTE
          type: string
          maxLength: 5
        category_name:
          description: nome della categoria dell'ENTE
          type: string
          maxLength: 140
        
    Error:
      $ref: './common/schemaError.yaml'      
    
  securitySchemes:
    $ref: './common/securitySchemes.yaml'

security:
  - bearerAuth: []