openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione delle SFE degli ENTI

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /SFE/{codice_uni_uo}:
    get:
      description: consultazione delle SFE dato il codice unico della UO

      operationId: getSFE

      parameters:
        - name: codice_uni_uo
          in: path
          description: codice unico della UO per il quale si effettua la ricerca
          required: true
          schema:
            $ref: '#/components/schemas/CodiceUniUO'
          example: 12345678901
            
      responses:
        '200':
          description: array JSON delle SFE
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SFE'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
  
components:

  responses:
    $ref: './common/response.yaml'

  schemas:
    CodiceFiscaleEnte:
      $ref: './common/schemaCodiceFiscaleEnte.yaml'

    CodiceUniUO:
      $ref: './common/schemaCodiceUniUO.yaml'

    SFE:
      description: UO di un ENTE
      type: object
      required:
        - codice_fiscale_ente
        - codice_ipa_ente
        - codice_uni_uo
        - descrizione_uo
        - codice_fiscale_sfe
        - data_verifica_cf
        - cod_peppol
        - data_avvio_sfe
      properties:
        codice_fiscale_ente:
          description: codice fiscale dell'ENTE
          $ref: '#/components/schemas/CodiceFiscaleEnte'
        codice_ipa_ente:
          description: codice IPA dell'ENTE
          $ref: '#/components/schemas/CodiceIPA'
        codice_uni_uo:
          $ref: '#/components/schemas/CodiceUniUO'
        descrizione_uo:
          type: string
          maxLength: 1000
        codice_fiscale_sfe:
          $ref: '#/components/schemas/CodiceFiscaleEnte'
        data_verifica_cf:
          type: string
          format: date                
        cod_peppol:
          type: string
          maxLength: 255
        data_avvio_sfe:
          type: string
          format: date
        
    CodiceIPA:
      $ref: './common/schemaCodiceIPA.yaml'

    Error:
      $ref: './common/schemaError.yaml'

  securitySchemes:
    $ref: './common/securitySchemes.yaml'

security:
  - bearerAuth: []