openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione degli aggiornamenti delle PEC degli ENTI alla specifica data

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /PECEnti/{date}:
    get:
      description: consultazione degli aggiornamenti delle PEC degli ENTI

      operationId: getPECEnti
      
      parameters:
        - name: date
          in: path
          description: Data variazioni
          required: true
          schema:
            type: string
            format: date

      responses:
        '200':
          description: array JSON delle PEC degli ENTI
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PECs'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
components:

  responses:
    '400':
      description: BAD_REQUEST
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '401':
      description: UNAUTHORIZED
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: FORBIDDEN
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: NOT_FOUND
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: INTERNAL_SERVER_ERROR
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '503':
      description: SERVICE_UNAVAILABLE
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    CodiceFiscaleEnte:
      description: Codice Fiscale dell'ENTE      
      type: string
      pattern: ^([0-9]{11})$
      example: 12345678901

    CodiceIPA:
      description: codice IPA dell'ENTE
      type: string
      maxLength: 100

    DigitalAddress:
      description: e-mail conforme a local-part@domain previsto da rfc5322
      type: string
      pattern: ^[a-zA-Z0-9!#$%&'*+\-\/=?^_`{|}~.]+@[a-zA-Z0-9!#$%&'*+\-\/=?^_`{|}~.]+\.[a-zA-Z0-9!#$%&'*+\-\/=?^_`{|}~.]+$
    
    PECs:
      description: array degli aggiornamenti delle PEC   
      type: array
      items:        
        type: object
        properties:       
          codice_fiscale_ente:
            $ref: '#/components/schemas/CodiceFiscaleEnte' 
          codice_ipa_ente:
            $ref: '#/components/schemas/CodiceIPA'  
          address:
            $ref: '#/components/schemas/DigitalAddress'
          operation:
            type: string
            maxLength: 1
            enum:
              - C
              - U
              - D
    
    Error:  
      description: Modello di risposta in caso di errore     
      
      type: object
      
      required:
        - status
        - typology      
      
      properties:
        status:
          type: string
          description: Codice di errore
          example: <HTTP_CODE>
          enum:
            - '400'
            - '401'
            - '403'
            - '404'
            - '500'
            - '503'
        typology:
          type: string
          description: Tipologia di errore
          example: <HTTP_STATUS>
          enum:
            - BAD_REQUEST
            - UNAUTHORIZED
            - FORBIDDEN
            - NOT_FOUND
            - INTERNAL_SERVER_ERROR
            - SERVICE_UNAVAILABLE
        detail:
          type: string
          description: Descrizione di dettaglio dello specifico problema verificatosi
          example: <detail_error>
      
    
  securitySchemes:
    bearerAuth:
      scheme: bearer
      bearerFormat: JWT
      type: http
      description: |-
        Implementazione conforme ad RFC8725
    

security:
  - bearerAuth: []