openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione degli aggiornamenti degli indirizzi delle UO alla specifica data

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /indirizziUOs/{date}:
    get:
      description: consultazione degli aggiornamenti dell'indirizzo delle UO

      operationId: getIndirizzoUO

      parameters:
        - name: date
          in: path
          description: Data variazioni
          required: true
          schema:
            type: string
            format: date

      responses:
        '200':
          description: elenco JSON indirizzi delle AO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Addresses'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
 
components:

  responses:
     '400':
       description: BAD_REQUEST
       content:
         application/problem+json:
           schema:
             $ref: '#/components/schemas/Error'
     '401':
       description: UNAUTHORIZED
       content:
         application/problem+json:
           schema:
             $ref: '#/components/schemas/Error'
     '403':
       description: FORBIDDEN
       content:
         application/problem+json:
           schema:
             $ref: '#/components/schemas/Error'
     '404':
       description: NOT_FOUND
       content:
         application/problem+json:
           schema:
             $ref: '#/components/schemas/Error'
     '500':
       description: INTERNAL_SERVER_ERROR
       content:
         application/problem+json:
           schema:
             $ref: '#/components/schemas/Error'
     '503':
       description: SERVICE_UNAVAILABLE
       content:
         application/problem+json:
           schema:
             $ref: '#/components/schemas/Error'

  schemas:
    CodiceUniUO:
      description: Codice unico dell'UO
      type: string
      maxLength: 6

    Addresses:
      description: elenco indirizzi
      type: array
      items:        
        type: object
        properties:       
          codice_uni_uo:
            $ref: '#/components/schemas/CodiceUniUO'   
          address:
            $ref: '#/components/schemas/Address'
          operation:
            type: string
            maxLength: 1
            enum:
              - C
              - U
              - D

    Address:
      description: Indirizzo della AOO
      required:       
        - codice_istat_comune
        - codice_catastale_comune
        - CAP
        - address
        
      type: object
      properties:        
        codice_istat_comune:
          description: codice istat del Comune della sede dell'ENTE
          type: string
          maxLength: 6        
        codice_catastale_comune:
          description: codice catastale del Comune della sede  dell'ENTE
          type: string
          maxLength: 4        
        CAP:
          description: CAP del Comune della sede dell'ENTE
          type: string
          pattern: ^([0-9]{5})$
        address:
          description: indirizzo della sede dell'ENTE
          type: string
          maxLength: 246 

    Error:  
      description: Modello di risposta in caso di errore     
      
      type: object
      
      required:
        - status
        - typology      
      
      properties:
        status:
          type: string
          description: Codice di errore
          example: <HTTP_CODE>
          enum:
            - '400'
            - '401'
            - '403'
            - '404'
            - '500'
            - '503'
        typology:
          type: string
          description: Tipologia di errore
          example: <HTTP_STATUS>
          enum:
            - BAD_REQUEST
            - UNAUTHORIZED
            - FORBIDDEN
            - NOT_FOUND
            - INTERNAL_SERVER_ERROR
            - SERVICE_UNAVAILABLE
        detail:
          type: string
          description: Descrizione di dettaglio dello specifico problema verificatosi
          example: <detail_error>
      
    
  securitySchemes:
    bearerAuth:
      scheme: bearer
      bearerFormat: JWT
      type: http
      description: |-
        Implementazione conforme ad RFC8725
    

security:
  - bearerAuth: []