openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione dei rappresentanti delle UO

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /rappresentateUO/{codice_uni_uo}:
    get:
      description: consultazione del reppresentate di una UO

      operationId: getRappresentate

      parameters:
        - name: codice_uni_uo
          in: path
          description: Codice unico dell'UO
          required: true
          schema:
            $ref: '#/components/schemas/CodiceUniUO'          
            
      responses:
        '200':
          description: reppresentate dell'UO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Representative'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'

  /status:
    get:      
      description: Ritorna lo stato dell'e-service in applicazione della [RAC_REST_NAME_011] delle Linee Guida sull’interoperabilità tecnica delle Pubbliche Amministrazioni
      operationId: getStatus
      responses:
        '200':
          description: Il servizio funziona correttamente
          content:
            'application/problem+json':
              schema:
                type: boolean
        '401':
          $ref: '#/components/responses/401'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
   
components:

  responses:
    '400':
      description: BAD_REQUEST
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '401':
      description: UNAUTHORIZED
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: NOT_FOUND
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: INTERNAL_SERVER_ERROR
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '503':
      description: SERVICE_UNAVAILABLE
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    CodiceUniUO:
      description: Codice unico dell'UO
      type: string
      maxLength: 6

    Representative:
      description: Rappresentate 
      required:
        - name
        - surname
        - role
        
      type: object
      properties:        
        name:
          description: nome del rappresentate dell'ENTE
          type: string
          maxLength: 50        
        surname:
          description: conome del rappresentate dell'ENTE
          type: string
          maxLength: 50        
        role:
          description: ruolo del rappresente dell'ENTE
          type: string
          maxLength: 100        

    Error:
      description: Modello di risposta in caso di errore     
      
      type: object
      
      required:
        - status
        - typology      
      
      properties:
        status:
          type: string
          description: Codice di errore
          example: <HTTP_CODE>
          enum:
            - '400'
            - '401'
            - '403'
            - '404'
            - '500'
            - '503'
        typology:
          type: string
          description: Tipologia di errore
          example: <HTTP_STATUS>
          enum:
            - BAD_REQUEST
            - UNAUTHORIZED
            - FORBIDDEN
            - NOT_FOUND
            - INTERNAL_SERVER_ERROR
            - SERVICE_UNAVAILABLE
        detail:
          type: string
          description: Descrizione di dettaglio dello specifico problema verificatosi
          example: <detail_error>

  securitySchemes:
    bearerAuth:
      scheme: bearer
      bearerFormat: JWT
      type: http
      description: |-
        Implementazione conforme ad RFC8725
    

security:
  - bearerAuth: []