openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione degli aggiornamenti dei domicili digitali delle UO alla specifica data

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /DDUOs/{date}:
    get:
      description: consultazione degli aggiornamenti dei domicili digitali delle UO alla data

      operationId: getDDUOs

      parameters:
        - name: date
          in: path
          description: Data variazioni
          required: true
          schema:
            type: string
            format: date

      responses:
        '200':
          description: elenco dei domicili digitali delle UO aggiornati
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DDs'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'

  /status:
    $ref: '../common/pathStatus.yaml'
    
components:

  responses:
    $ref: '../common/response.yaml'

  schemas:
    CodiceUniUO:
      $ref: '../common/schemaCodiceUniUO.yaml'

    DigitalAddress:
      $ref: '../common/schemaDigitalAddress.yaml'

    DDs:            
      type: array
      required:
        - codice_uni_uo
        - DD        
        - operation
      items:
        type: object
        properties:       
          codice_uni_uo:
            $ref: '#/components/schemas/CodiceUniUO'   
          DD:
            $ref: '#/components/schemas/DigitalAddress'
          operation:
            $ref: '../common/schemaOperation.yaml'
    
    Error: 
      $ref: '../common/schemaError.yaml'
      
    
  securitySchemes:
    $ref: '../common/securitySchemes.yaml'

security:
  - bearerAuth: []