openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per l'aggiornamento delle UO alla specifica data

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /UOs/{date}:
    get:
      description: consultazione degli aggiornamenti delle UO alla data

      operationId: getUOs

      parameters:
        - name: date
          in: path
          description: Data variazioni
          required: true
          schema:
            type: string
            format: date
           
      responses:
        '200':
          description: elenco delle UO aggiornate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UOs'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'

  /status:
    $ref: '../common/pathStatus.yaml'  
  
components:

  responses:
    $ref: '../common/response.yaml'

  schemas:
    CodiceFiscaleEnte:
      $ref: '../common/schemaCodiceFiscaleEnte.yaml'

    CodiceUniUO:
      $ref: '../common/schemaCodiceUniUO.yaml'      

    UOs:
      type: array
      required:
        - UO
        - operation
      items:        
        type: object
        properties:       
          UO:
            $ref: '#/components/schemas/UO'             
          operation:
            $ref: '../common/schemaOperation.yaml'
    UO:
      $ref: '../common/schemaUO.yaml'

    CodiceIPA:
      $ref: '../common/schemaCodiceIPA.yaml'

    Error:  
      $ref: '../common/schemaError.yaml'      
    
  securitySchemes:
    $ref: '../common/securitySchemes.yaml'

security:
  - bearerAuth: []