openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione degli aggiornamenti degli indirizzi delle AOO alla specifica data
    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /indirizziAOOs/{date}:
    get:
      description: consultazione degli aggiornamenti degli indirizzi delle AOO alla data

      operationId: getIndirizzoAOO

      parameters:
        - name: date
          in: path
          description: Data variazioni
          required: true
          schema:
            type: string
            format: date

      responses:
        '200':
          description: elenco degli indirizzi delle AOO aggiornati
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Addresses'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'

  /status:
    $ref: '../common/pathStatus.yaml'  
 
components:

  responses:
    $ref: '../common/response.yaml'

  schemas:
    CodiceUniAOO:
      $ref: '../common/schemaCodiceUniAOO.yaml'

    Addresses:
      description: elenco indirizzi
      type: array
      required:
        - codice_uni_aoo
        - address
        - operation
      items:        
        type: object
        properties:       
          codice_uni_aoo:
            $ref: '#/components/schemas/CodiceUniAOO'   
          address:
            $ref: '#/components/schemas/Address'
          operation:
            $ref: '../common/schemaOperation.yaml'

    Address:
      $ref: '../common/schemaAddress.yaml'

    Error:  
      $ref: '../common/schemaError.yaml'
      
    
  securitySchemes:
    $ref: '../common/securitySchemes.yaml'

security:
  - bearerAuth: []