openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione delle AOO correnti

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /AOOs:
    get:
      description: consultazione delle AOO correnti
      
      operationId: getAOOs    
            
      responses:
        '200':
          description: elenco delle AOO correnti
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AOOs'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'

  /status:
    $ref: '../common/pathStatus.yaml'

components:

  responses:
    $ref: '../common/response.yaml'

  schemas:    
    CodiceUniAOO:
      $ref: '../common/schemaCodiceUniAOO.yaml'

    AOOs:      
      type: array
      items:
        type: object
        required:
          - AOO          
        properties:
          AOO: 
            $ref: '#/components/schemas/AOO'
          
    AOO:
      $ref: '../common/schemaAOO.yaml'

    Error:
      $ref: '../common/schemaError.yaml'
    
  securitySchemes:
    $ref: '../common/securitySchemes.yaml'

security:
  - bearerAuth: []