openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione degli aggiornamenti degli ENTI alla specifica data

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /enti/{date}:
    get:
      description: consultazione degli aggiornamenti degli ENTI

      operationId: getEntes

      parameters:
        - name: date
          in: path
          description: Data variazioni
          required: true
          schema:
            type: string
            format: date
       
      responses:
        '200':
          description: JSON dell'ENTE estratto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enti'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
 
components:

  responses:
    $ref: '../common/response.yaml'

  schemas:
    CodiceFiscaleEnte:
      $ref: '../common/schemaCodiceFiscaleEnte.yaml'

    CodiceIPA:
      $ref: '../common/schemaCodiceIPA.yaml'

    DigitalAddress:
      $ref: '../common/schemaDigitalAddress.yaml'

    Enti:
      description: elenco degli Enti aggiornamenti
      type: array
      items:
        type: object
        required:
          - ente
          - operation
        properties:
          Ente: 
            $ref: '#/components/schemas/Ente'
          operation:  
            $ref: '../common/schemaOperation.yaml'

    Ente:
      $ref: '../common/schemaEnte.yaml'

    Error:
      $ref: '../common/schemaError.yaml'

    
  securitySchemes:
     $ref: '../common/securitySchemes.yaml'

security:
  - bearerAuth: []